"""

Revision ID: f61fd1b907c6
Revises: 83f5f5bc3f0d
Create Date: 2026-06-24 17:36:18.713052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f61fd1b907c6'
down_revision: Union[str, Sequence[str], None] = '83f5f5bc3f0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('status', sa.Enum('pending', 'ordered', 'shipped', 'delivered', name='orderstatus'), nullable=False))
    op.drop_column('orders', 'order_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('order_date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('order_items', 'status')
    # ### end Alembic commands ###
